package vistas;

import Recursos.Propietario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus X505B
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    Propietario Pro;
    public static ArrayList<Propietario> Prop = new ArrayList<Propietario>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idpro = new javax.swing.JTextField();
        nomP = new javax.swing.JTextField();
        emailP = new javax.swing.JTextField();
        TelefP = new javax.swing.JTextField();
        ApellP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Guardar = new javax.swing.JButton();
        Inmueble = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Propietarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 260, 70));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Apellido Propietario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nombre Propietarios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("IdPropietario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Email Propietario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Telefono Propietario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(idpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 130, 30));
        getContentPane().add(nomP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 30));
        getContentPane().add(emailP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 130, 30));
        getContentPane().add(TelefP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 30));
        getContentPane().add(ApellP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 130, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPropietario", "Nombre del Propietario", "Apellido del Propietarios       ", "Email Propietario", "Telefono del propietario"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 590, 210));

        Guardar.setBackground(new java.awt.Color(51, 255, 255));
        Guardar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(51, 255, 255)));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 120, 40));

        Inmueble.setBackground(new java.awt.Color(153, 255, 255));
        Inmueble.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Inmueble.setText("Ir a Inmueble");
        Inmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InmuebleActionPerformed(evt);
            }
        });
        getContentPane().add(Inmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wepik-20211021-221738.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        int IdPropietario;
        String NombrePropietario;
        String ApellidoPropietario;
        String EmailPropietario;
        int TelefonoPropietario;

        IdPropietario = Integer.parseInt(idpro.getText());
        NombrePropietario = nomP.getText();
        ApellidoPropietario = ApellP.getText();
        EmailPropietario = emailP.getText();
        TelefonoPropietario = Integer.parseInt(TelefP.getText());
        
        Pro = new Propietario(IdPropietario,NombrePropietario,ApellidoPropietario,EmailPropietario,TelefonoPropietario );
        Prop.add(Pro);
        
        jTable1.setModel(Pro.MostrarPro(Prop));
        
        idpro.setText("");
        nomP.setText("");
        ApellP.setText("");
        emailP.setText("");
        TelefP.setText("");
    }//GEN-LAST:event_GuardarActionPerformed

    private void InmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InmuebleActionPerformed
        // TODO add your handling code here:
        Parte3 sig = new Parte3();
        sig.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InmuebleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellP;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Inmueble;
    private javax.swing.JTextField TelefP;
    private javax.swing.JTextField emailP;
    private javax.swing.JTextField idpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField nomP;
    // End of variables declaration//GEN-END:variables
}
