/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Recursos.Conjunto;
import Recursos.Inmueble;
import Recursos.Propietario;
import Recursos.Invent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static vistas.Inicio.Prop;
import static vistas.Inicio.jTable1;

/**
 *
 * @author Asus X505B
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    ArrayList<Propietario> Prop = new ArrayList<Propietario>();
    Propietario Pro;

    ArrayList<Conjunto> Conjunt = new ArrayList<Conjunto>();
    Conjunto Conj;

    ArrayList<Inmueble> Inmb = new ArrayList<Inmueble>();
    Inmueble In;

    Invent nuevo;
    public static ArrayList<Invent> logros = new ArrayList<Invent>();

    public Inventario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Inventario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 250, 60));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Usuario"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Digite el nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 30));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 30));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel4.setText("Digite el Numero Apto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 120, 30));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 450, 130));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "idProp", "Nombre Prop", "Apellido Pro", "Idmueb  ", "TorreMueb   ", " NumAptomueble", " idcon", " nombConj"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 630, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wepik-20211021-221738.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String user = jTextField2.getText();
        String NomPro, Apellido;
        int id = 1;
        int idpro;
        int idmueb;
        int TorreMueb;
        int NumAptomueble;
        int idconj;
        String nombConj;
        for (int i = 0; i < Inicio.Prop.size(); i++) {
            Pro = Inicio.Prop.get(i);
            idpro = Pro.getIdPropietario();
            NomPro = Pro.getNombrePropietario();
            Apellido = Pro.getApellidoPropietario();
            for (int a = 0; a < Parte3.Inmb.size(); a++) {
                In = Parte3.Inmb.get(a);
                idmueb = In.getIdmueble();
                TorreMueb = In.getTorre();
                NumAptomueble = In.getNumeroApto();
                for (int b = 0; b < Parte2.Conjunt.size(); b++) {
                    Conj = Parte2.Conjunt.get(b);
                    idconj = Conj.getIdConjunto();
                    nombConj = Conj.getNombreConjunto();
                    if (user.equals(NomPro)) {
                        nuevo = new Invent(id,idpro, NomPro, Apellido, idmueb, TorreMueb, NumAptomueble, idconj,nombConj );
                        logros.add(nuevo);

                        jTable1.setModel(nuevo.MostrarInvent(logros));
                        id = id + 1;
                    }
                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int user = Integer.parseInt(jTextField3.getText());
        String NomPro, Apellido;
        int id = 1;
        int idpro;
        int idmueb;
        int TorreMueb;
        int NumAptomueble;
        int idconj;
        String nombConj;
        for (int i = 0; i < Inicio.Prop.size(); i++) {
            Pro = Inicio.Prop.get(i);
            idpro = Pro.getIdPropietario();
            NomPro = Pro.getNombrePropietario();
            Apellido = Pro.getApellidoPropietario();
            for (int a = 0; a < Parte3.Inmb.size(); a++) {
                In = Parte3.Inmb.get(a);
                idmueb = In.getIdmueble();
                TorreMueb = In.getTorre();
                NumAptomueble = In.getNumeroApto();
                for (int b = 0; b < Parte2.Conjunt.size(); b++) {
                    Conj = Parte2.Conjunt.get(b);
                    idconj = Conj.getIdConjunto();
                    nombConj = Conj.getNombreConjunto();
                    if (user==NumAptomueble) {
                        nuevo = new Invent(id,idpro, NomPro, Apellido, idmueb, TorreMueb, NumAptomueble, idconj,nombConj );
                        logros.add(nuevo);

                        jTable1.setModel(nuevo.MostrarInvent(logros));
                        id = id + 1;
                    }
                }

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
