/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Recursos.Conjunto;
import java.util.ArrayList;

/**
 *
 * @author Asus X505B
 */
public class Parte2 extends javax.swing.JFrame {

    /**
     * Creates new form Conjunto
     */
    public Parte2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    Conjunto Conj;
    public static ArrayList<Conjunto> Conjunt = new ArrayList<Conjunto>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idConj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NombreC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NIT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Dirc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TeleConj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Guardar = new javax.swing.JButton();
        Inventario = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Conjuntos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 260, 70));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("IdConjunto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(idConj, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nombre del Conjunto: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(NombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("NIT del Conjunto: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(NIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 130, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Direccion del Conjunto: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(Dirc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 130, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Telefono del Conjunto: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(TeleConj, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 30));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idConjunto", "Nombre del Conjunto", "Nit Conjunto", "Direccion Conjunto", "Telefono del Conjunto"
            }
        ));
        jScrollPane1.setViewportView(jTable3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 590, 210));

        Guardar.setBackground(new java.awt.Color(51, 255, 255));
        Guardar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(51, 255, 255)));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 120, 40));

        Inventario.setBackground(new java.awt.Color(153, 255, 255));
        Inventario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Inventario.setText("Ir a Inventario");
        Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioActionPerformed(evt);
            }
        });
        getContentPane().add(Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wepik-20211021-221738.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 612, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        int IdConjunto;
        String NombreConjunto;
        String NitConjunto;
        String DireccionConjunto;
        int TelefonoConjunto;

        IdConjunto = Integer.parseInt(idConj.getText());
        NombreConjunto = NombreC.getText();
        NitConjunto = NIT.getText();
        DireccionConjunto = Dirc.getText();
        TelefonoConjunto = Integer.parseInt(TeleConj.getText());

        Conj = new Conjunto(IdConjunto,NombreConjunto,NitConjunto,DireccionConjunto,TelefonoConjunto);
        Conjunt.add(Conj);

        jTable3.setModel(Conj.MostrarConj(Conjunt));

        idConj.setText("");
        NombreC.setText("");
        NIT.setText("");
        Dirc.setText("");
        TeleConj.setText("");
    }//GEN-LAST:event_GuardarActionPerformed

    private void InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioActionPerformed
        // TODO add your handling code here:
        Inventario sig = new Inventario();
        sig.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parte2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dirc;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Inventario;
    private javax.swing.JTextField NIT;
    private javax.swing.JTextField NombreC;
    private javax.swing.JTextField TeleConj;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField idConj;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
