/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Recursos.Inmueble;
import java.util.ArrayList;
import static vistas.Inicio.Prop;
import static vistas.Inicio.jTable1;

/**
 *
 * @author Asus X505B
 */
public class Parte3 extends javax.swing.JFrame {

    /**
     * Creates new form Inmueble
     */
    public Parte3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    Inmueble In;
    public static ArrayList<Inmueble> Inmb = new ArrayList<Inmueble>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idmueble = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        torre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Guardar = new javax.swing.JButton();
        Conjunto = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Inmuebles");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 260, 70));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Idmueble");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(idmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Torre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, -1));
        getContentPane().add(torre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 130, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Numero Apto: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(apto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idmueble", "Torre", "NumeroApto"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 410, 160));

        Guardar.setBackground(new java.awt.Color(51, 255, 255));
        Guardar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(51, 255, 255)));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 120, 40));

        Conjunto.setBackground(new java.awt.Color(153, 255, 255));
        Conjunto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Conjunto.setText("Ir a Conjunto");
        Conjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConjuntoActionPerformed(evt);
            }
        });
        getContentPane().add(Conjunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 140, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wepik-20211021-221738.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        int Idmueble,Torre,NumeroApto;


        Idmueble = Integer.parseInt(idmueble.getText());
        Torre = Integer.parseInt(torre.getText());
        NumeroApto= Integer.parseInt(apto.getText());

        In = new Inmueble(Idmueble, Torre, NumeroApto);
        Inmb.add(In);
        
         jTable2.setModel(In.MostrarInm(Inmb));
        
        idmueble.setText("");
        torre.setText("");
        apto.setText("");
    }//GEN-LAST:event_GuardarActionPerformed

    private void ConjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConjuntoActionPerformed
        // TODO add your handling code here:
        Parte2 sig = new Parte2();
        sig.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ConjuntoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parte3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Conjunto;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField apto;
    private javax.swing.JTextField idmueble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable2;
    private javax.swing.JTextField torre;
    // End of variables declaration//GEN-END:variables
}
