/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import java.awt.Color;
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        setSize(612, 612);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Atras3 = new javax.swing.JButton();
        Encabezado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RegNombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RegApellidos = new javax.swing.JTextField();
        RegCedula = new javax.swing.JTextField();
        RegTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RegCorreo = new javax.swing.JTextField();
        RegPass = new javax.swing.JPasswordField();
        RegGuadar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Atras3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        Atras3.setAutoscrolls(true);
        Atras3.setBorderPainted(false);
        Atras3.setContentAreaFilled(false);
        getContentPane().add(Atras3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        Encabezado.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        Encabezado.setText("Registro De Farmaceuticos  ");
        getContentPane().add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 280, 40));

        jLabel2.setBackground(java.awt.Color.yellow);
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.orange);
        jLabel2.setText("Nombres ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel1.setBackground(java.awt.Color.yellow);
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.orange);
        jLabel1.setText("Apellidos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 70, 20));

        jLabel3.setBackground(java.awt.Color.yellow);
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.orange);
        jLabel3.setText("Cedula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, -1));

        jLabel4.setBackground(java.awt.Color.yellow);
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.orange);
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 80, -1));

        RegNombres.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(RegNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 150, 30));

        jLabel5.setBackground(java.awt.Color.yellow);
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.orange);
        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        RegApellidos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(RegApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 150, 30));

        RegCedula.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(RegCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 150, 30));

        RegTelefono.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(RegTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 150, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.orange);
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        RegCorreo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(RegCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 150, 30));

        RegPass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(RegPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 150, 30));

        RegGuadar.setBackground(java.awt.Color.orange);
        RegGuadar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        RegGuadar.setText("Guardar");
        getContentPane().add(RegGuadar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 100, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo2.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras3;
    private javax.swing.JLabel Encabezado;
    private javax.swing.JLabel Fondo;
    public javax.swing.JTextField RegApellidos;
    public javax.swing.JTextField RegCedula;
    public javax.swing.JTextField RegCorreo;
    public javax.swing.JButton RegGuadar;
    public javax.swing.JTextField RegNombres;
    public javax.swing.JPasswordField RegPass;
    public javax.swing.JTextField RegTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
