/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus X505B
 */
public class Vender extends javax.swing.JFrame {

    /**
     * Creates new form Vender
     */
    public Vender() {
        initComponents();
        setSize(610, 350);
        setTitle("Farmaceutica StarsGold");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CODE = new javax.swing.JTextField();
        VDBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CANTIDAD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        VALOR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TIPO_VALOR = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        VENTA = new javax.swing.JTextField();
        VENDER = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        INFORME = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        Atras2 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 50, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Buscar Medicamento A Vender");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 260, 70));
        getContentPane().add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Codigo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 40, 40));
        getContentPane().add(CODE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 100, 30));

        VDBuscar.setBackground(new java.awt.Color(51, 255, 0));
        VDBuscar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        VDBuscar.setText("Buscar");
        getContentPane().add(VDBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Cantidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 20));
        getContentPane().add(CANTIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 100, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Valor $");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 50, 20));
        getContentPane().add(VALOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 100, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Vender Por:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 80, 20));
        getContentPane().add(TIPO_VALOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 100, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 570, 20));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 370, 20));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 20, 140));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Cantidad A Vender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 150, 30));
        getContentPane().add(VENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 70, 30));

        VENDER.setBackground(new java.awt.Color(0, 255, 0));
        VENDER.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        VENDER.setText("Vender");
        getContentPane().add(VENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 90, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Informacion Del Producto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));
        getContentPane().add(INFORME, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 100));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 70, 30));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 90, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Cambio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 70, 20));
        getContentPane().add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 110, 30));
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 50, -1));

        Atras2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Atras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        Atras2.setAutoscrolls(true);
        Atras2.setBorderPainted(false);
        Atras2.setContentAreaFilled(false);
        Atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras2ActionPerformed(evt);
            }
        });
        getContentPane().add(Atras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Paneles.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras2ActionPerformed
        Inicio In = new Inicio();
        In.setLocationRelativeTo(null);
        In.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Atras2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras2;
    public javax.swing.JTextField CANTIDAD;
    public javax.swing.JTextField CODE;
    private javax.swing.JLabel Fondo;
    public javax.swing.JTextField ID;
    public javax.swing.JTextField INFORME;
    public javax.swing.JTextField NOMBRE;
    public javax.swing.JTextField TIPO_VALOR;
    public javax.swing.JTextField VALOR;
    public javax.swing.JButton VDBuscar;
    public javax.swing.JButton VENDER;
    public javax.swing.JTextField VENTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JTextField txtCambio;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
