/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import static Vistas.Radio_Button.SLEdad;
import static Vistas.Radio_Button.TFDireccion;
import static Vistas.Radio_Button.TFname;

/**
 *
 * @author Asus X505B
 */
public class Check_Box extends javax.swing.JFrame {

    /**
     * Creates new form Check_Box
     */
    public Check_Box() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione Sus Gustos Musicales");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 270, 40));

        jCheckBox1.setText("POP");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jCheckBox2.setText("Rock");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jCheckBox3.setText("reggaeton");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jCheckBox4.setText("Jazz");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jCheckBox5.setText("Cumbia");
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, -1));

        jCheckBox6.setText("rap ");
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jCheckBox7.setText("champeta");
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jCheckBox8.setText("rancheras");
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jCheckBox9.setText("Baladas ");
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jCheckBox10.setText("Boleros");
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jCheckBox11.setText("vallenato");
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jCheckBox12.setText("hip hop");
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Guardar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 130, 40));

        jLabel1.setText("Puede Elegir Varios Generos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/5648352.jpg"))); // NOI18N
        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Combo_Box Nueva = new Combo_Box();
        Nueva.setVisible(true);
        this.setVisible(false);
        
        //Datos Del Usuario
        Combo_Box.Ventada2Name.setText(TFname.getText());
        Combo_Box.Ventana2Direccion.setText("Direccion: "+TFDireccion.getText());
        Combo_Box.Ventana2Sexo.setText("Edad: "+SLEdad.getValue()+" Años");
               
        
        //Gustos Del Usuario
        if(jCheckBox1.isSelected()){
         Combo_Box.POP.setText(jCheckBox1.getText()+"\n");   
        }
        if(jCheckBox2.isSelected()){
             Combo_Box.cumbia.setText(jCheckBox2.getText()+"\n");
        }     
        if(jCheckBox3.isSelected()){
            Combo_Box.baladas.setText(jCheckBox3.getText()+"\n");
        }
        if(jCheckBox4.isSelected()){
         Combo_Box.rock.setText(jCheckBox4.getText()+"\n");   
        }
        if(jCheckBox5.isSelected()){
            Combo_Box.Regeton.setText(jCheckBox5.getText()+"\n");
        }
        if(jCheckBox6.isSelected()){
            Combo_Box.bolero.setText(jCheckBox6.getText()+"\n");
        }
        if(jCheckBox7.isSelected()){
            Combo_Box.jazz.setText(jCheckBox7.getText()+"\n");
        }
        if(jCheckBox8.isSelected()){
            Combo_Box.champeta.setText(jCheckBox8.getText()+"\n");
        }
        if(jCheckBox9.isSelected()){
            Combo_Box.ranchera.setText(jCheckBox9.getText()+"\n");
        }
        if(jCheckBox10.isSelected()){
            Combo_Box.rap.setText(jCheckBox10.getText()+"\n");
        }
        if(jCheckBox11.isSelected()){
            Combo_Box.vallenato.setText(jCheckBox11.getText()+"\n");
        }
        if(jCheckBox12.isSelected()){
         Combo_Box.hiphop.setText(jCheckBox12.getText()+"\n");
        }
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_Box.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_Box.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_Box.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_Box.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_Box().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
