/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Vistas.Combo_Box;
/**
 *
 * @author Asus X505B
 */
public class Radio_Button extends javax.swing.JFrame {

    /**
     * Creates new form Radio_Button
     */
    public Radio_Button() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Masc = new javax.swing.JRadioButton();
        Femen = new javax.swing.JRadioButton();
        Sex = new javax.swing.JLabel();
        JLtitulo = new javax.swing.JLabel();
        TFname = new javax.swing.JTextField();
        JLname = new javax.swing.JLabel();
        JLedad = new javax.swing.JLabel();
        TFDireccion = new javax.swing.JTextField();
        SLEdad = new javax.swing.JSlider();
        JLprintEdad = new javax.swing.JLabel();
        JLdireccion = new javax.swing.JLabel();
        JLcorreo = new javax.swing.JLabel();
        TFcorreo = new javax.swing.JTextField();
        JLPass = new javax.swing.JLabel();
        JPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        Icon = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.SystemColor.inactiveCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Sexo.add(Masc);
        Masc.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        Masc.setText("Masculino");

        Sexo.add(Femen);
        Femen.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        Femen.setText("Femenino");

        Sex.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        Sex.setText("Sexo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Masc)
                .addGap(41, 41, 41)
                .addComponent(Femen)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Masc)
                    .addComponent(Femen)
                    .addComponent(Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 340, 80));

        JLtitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JLtitulo.setText("Formulario De Registro");
        getContentPane().add(JLtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 290, 40));
        getContentPane().add(TFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 200, 30));

        JLname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLname.setText("Nombre Completo:");
        getContentPane().add(JLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, 30));

        JLedad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLedad.setText("Arrastre:");
        getContentPane().add(JLedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, 30));
        getContentPane().add(TFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, 30));

        SLEdad.setBackground(new java.awt.Color(255, 255, 255));
        SLEdad.setMajorTickSpacing(8);
        SLEdad.setMaximum(78);
        SLEdad.setMinimum(18);
        SLEdad.setPaintLabels(true);
        SLEdad.setPaintTicks(true);
        SLEdad.setValue(0);
        SLEdad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SLEdadStateChanged(evt);
            }
        });
        getContentPane().add(SLEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 200, 40));

        JLprintEdad.setText("Edad: 18 Años");
        getContentPane().add(JLprintEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 90, 40));

        JLdireccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLdireccion.setText("Direccion:");
        getContentPane().add(JLdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 30));

        JLcorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLcorreo.setText("Correo:");
        getContentPane().add(JLcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 90, 30));
        getContentPane().add(TFcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 200, 30));

        JLPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLPass.setText("Contraseña");
        getContentPane().add(JLPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 30));
        getContentPane().add(JPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 200, 30));

        jButton1.setBackground(java.awt.SystemColor.activeCaption);
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 120, 40));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/addusergroup_1251.png"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 120, 110));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo2.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SLEdadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SLEdadStateChanged
        // Codigo Del Slider
        JLprintEdad.setText("Edad: "+SLEdad.getValue()+" Años");
    }//GEN-LAST:event_SLEdadStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Combo_Box Sigiente = new Combo_Box();
        Sigiente.setVisible(true);
        this.setVisible(false);
        
        Combo_Box.Ventada2Name.setText(TFname.getText());
        Combo_Box.Ventana2Direccion.setText("Direccion: "+TFDireccion.getText());
        Combo_Box.Ventana2Sexo.setText("Edad: "+SLEdad.getValue()+" Años");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Radio_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Radio_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Radio_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Radio_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Radio_Button().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton Femen;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel JLPass;
    private javax.swing.JLabel JLcorreo;
    private javax.swing.JLabel JLdireccion;
    private javax.swing.JLabel JLedad;
    private javax.swing.JLabel JLname;
    private javax.swing.JLabel JLprintEdad;
    private javax.swing.JLabel JLtitulo;
    public static javax.swing.JPasswordField JPass;
    public static javax.swing.JRadioButton Masc;
    public static javax.swing.JSlider SLEdad;
    private javax.swing.JLabel Sex;
    public javax.swing.ButtonGroup Sexo;
    public static javax.swing.JTextField TFDireccion;
    public static javax.swing.JTextField TFcorreo;
    public static javax.swing.JTextField TFname;
    private javax.swing.JLabel fondo2;
    private javax.swing.JButton jButton1;
    public static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
