/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Asus X505B
 */
public class Scroll_Bar extends javax.swing.JFrame {

    /**
     * Creates new form Scroll_Bar
     */
    
    int ganadas=0;int perdidas=0;
    public Scroll_Bar() {
        initComponents();
        SpinnerNumberModel modeloSpinner = new SpinnerNumberModel();
        modeloSpinner.setMaximum(10);
        modeloSpinner.setMinimum(0);
        jSpinner1.setModel(modeloSpinner);
        
        
        this.setLocationRelativeTo(this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        azar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        impazar = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ganar = new javax.swing.JLabel();
        Perder = new javax.swing.JLabel();
        Fondo5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Juego De Azar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 180, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero Anterior: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 30));

        azar.setBackground(new java.awt.Color(0, 255, 255));
        azar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        azar.setText("Generar");
        azar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azarActionPerformed(evt);
            }
        });
        getContentPane().add(azar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 100, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecione un numero entre 1 y 10 para jugar.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Si su numero es igual al numero generado por la maquina usted gana, sino Usted PIERDE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 530, 30));

        impazar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        impazar.setForeground(new java.awt.Color(0, 255, 51));
        getContentPane().add(impazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 60, 30));

        jSpinner1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jSpinner1.setMaximumSize(new java.awt.Dimension(10, 10));
        jSpinner1.setMinimumSize(new java.awt.Dimension(1, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("Partidas Ganadas: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 110, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Partidas Perdidas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 120, 40));

        ganar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ganar.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(ganar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 60, 30));

        Perder.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Perder.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(Perder, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 60, 30));

        Fondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo3.jpg"))); // NOI18N
        getContentPane().add(Fondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void azarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azarActionPerformed
         int numero = (int)(Math.random()*10+1);
         impazar.setText(""+numero+"");
         int azar = (Integer) jSpinner1.getValue();
         if(azar== numero){
             JOptionPane.showMessageDialog(null, "Felicidades Haz Ganado");
             ganadas=ganadas+1;
             ganar.setText(""+ganadas+"");
         }else{
             JOptionPane.showMessageDialog(null, "Ha Perdido, Intente Nuevamente");
             perdidas=perdidas+1;
             Perder.setText(""+perdidas+"");
         }
    }//GEN-LAST:event_azarActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
       
    }//GEN-LAST:event_jSpinner1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scroll_Bar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scroll_Bar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scroll_Bar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scroll_Bar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scroll_Bar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo5;
    private javax.swing.JLabel Perder;
    private javax.swing.JButton azar;
    private javax.swing.JLabel ganar;
    private javax.swing.JLabel impazar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
