/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus X505B
 */
public class Bebidas extends javax.swing.JFrame {

    /** Creates new form Bebidas */
    public Bebidas() {
        initComponents();
        this.setTitle("Bebidas");
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("../img/iconinit2.png")).getImage());
        this.setLocationRelativeTo(this);
    }
    
     void limpiar(){
        jTextField1.setText("");
        tipo.setSelectedIndex(0);
        nombrebebida.setSelectedIndex(0);
        jSlider1.setValue(0);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        nombrebebida = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de Bebida");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nombre de bebida");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Valor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 110, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder-waterglassdrinkglass-of-waterfood-and-restauranthealthy-foodliquidfood-4394765_119490.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beverageserveservicepremiumrestaurant_109741.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 110, 70));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Bebidas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, 40));

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua", "Gaseosas", "Zumos de frutas", "Cafeína", "Alcohol" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, 30));

        getContentPane().add(nombrebebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Cantidad");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 40));

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(8);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(1);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 150, 30));

        jButton1.setBackground(java.awt.SystemColor.inactiveCaption);
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 90, 30));

        jButton2.setBackground(java.awt.SystemColor.inactiveCaption);
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 100, 30));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 70, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 471));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        String opcion = tipo.getSelectedItem().toString();
        if(opcion=="Agua"){
            nombrebebida.removeAllItems();
            nombrebebida.addItem("Agua Con Gas");
            nombrebebida.addItem("Agua Natural");
        }else if(opcion=="Gaseosas"){
            nombrebebida.removeAllItems();
            nombrebebida.addItem("Postobon Manzana");
            nombrebebida.addItem("Postobon Fresa");
            nombrebebida.addItem("Postobon Cola");
            nombrebebida.addItem("Pepsi");
            nombrebebida.addItem("fanta mezzo");
            nombrebebida.addItem("coca cola cherry");
        }else if(opcion=="Zumos de frutas"){
            nombrebebida.removeAllItems();
            nombrebebida.addItem("Naranja");
            nombrebebida.addItem("Manzana");
            nombrebebida.addItem("Piña");
            nombrebebida.addItem("Melocoton");
            nombrebebida.addItem("Platano");
            nombrebebida.addItem("Uva");
        }else if(opcion=="Cafeína"){
            nombrebebida.removeAllItems();
            nombrebebida.addItem("Café");
            nombrebebida.addItem("Té");
            nombrebebida.addItem("Instantáneo");
            nombrebebida.addItem("Chocolate");
            nombrebebida.addItem("Espresso");
            nombrebebida.addItem("Descafeinado");
        }else if(opcion=="Alcohol"){
            nombrebebida.removeAllItems();
            nombrebebida.addItem("Whisky");
            nombrebebida.addItem("Vodka");
            nombrebebida.addItem("Tequila");
            nombrebebida.addItem("Ron");
            nombrebebida.addItem("Brandy");
            nombrebebida.addItem("Ginebra");
        }
    }//GEN-LAST:event_tipoActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        jLabel9.setText(" "+jSlider1.getValue()+" Bebidas");
    }//GEN-LAST:event_jSlider1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String nombre, type, valor;
       int cantidad;
       
       type = tipo.getSelectedItem().toString();
       nombre = nombrebebida.getSelectedItem().toString();
       cantidad = jSlider1.getValue();
       valor = jTextField1.getText();
       JOptionPane.showMessageDialog(null, "Tipo de Bebida: "+type+"\n"+"Nombre de la bebida: "+nombre+"\n"+"Cantidad: "+cantidad+"\n"+"Valor $: "+valor);
       JOptionPane.showMessageDialog(null, "Guardados Correctamente");
       limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> nombrebebida;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables

}
