package vistas;

import javax.swing.ImageIcon;

/**
 *
 * @author Asus X505B
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("../img/iconinit.png")).getImage());
        this.setLocationRelativeTo(this);
        this.setTitle("Restaurante Arzak");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        platos = new javax.swing.JButton();
        iconplato = new javax.swing.JLabel();
        Adicional = new javax.swing.JButton();
        iconadici = new javax.swing.JLabel();
        iconbebida = new javax.swing.JLabel();
        bebida = new javax.swing.JButton();
        iconpostre = new javax.swing.JLabel();
        postre = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Titulo.setText("Restaurante Arzak");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 160, 40));

        platos.setBackground(java.awt.SystemColor.inactiveCaption);
        platos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        platos.setText("Platos Principales");
        platos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platosActionPerformed(evt);
            }
        });
        getContentPane().add(platos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, 50));

        iconplato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1486071980-1_79325.png"))); // NOI18N
        getContentPane().add(iconplato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 90));

        Adicional.setBackground(java.awt.SystemColor.inactiveCaption);
        Adicional.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Adicional.setText("Platos Adicionales");
        Adicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionalActionPerformed(evt);
            }
        });
        getContentPane().add(Adicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, 50));

        iconadici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foodmealplaterestaurant_109684.png"))); // NOI18N
        getContentPane().add(iconadici, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, 110));

        iconbebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beverageserveservicepremiumrestaurant_109741.png"))); // NOI18N
        getContentPane().add(iconbebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 100, -1));

        bebida.setBackground(java.awt.SystemColor.inactiveCaption);
        bebida.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bebida.setText("Bebidas");
        bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidaActionPerformed(evt);
            }
        });
        getContentPane().add(bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 140, 50));

        iconpostre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/free-30-instagram-stories-icons72_122619.png"))); // NOI18N
        getContentPane().add(iconpostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 90, 80));

        postre.setBackground(java.awt.SystemColor.inactiveCaption);
        postre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        postre.setText("Postres");
        postre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postreActionPerformed(evt);
            }
        });
        getContentPane().add(postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 130, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void platosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platosActionPerformed
        Plato_Principal Sig = new Plato_Principal();
        Sig.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_platosActionPerformed

    private void postreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postreActionPerformed
        Postre Sig2 = new Postre();
        Sig2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_postreActionPerformed

    private void bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidaActionPerformed
        Bebidas Sig3 = new Bebidas();
        Sig3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bebidaActionPerformed

    private void AdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionalActionPerformed
        Adicionales Sig4 = new Adicionales();
        Sig4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdicionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicional;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton bebida;
    private javax.swing.JLabel iconadici;
    private javax.swing.JLabel iconbebida;
    private javax.swing.JLabel iconplato;
    private javax.swing.JLabel iconpostre;
    private javax.swing.JButton platos;
    private javax.swing.JButton postre;
    // End of variables declaration//GEN-END:variables
}
