package restaurante_arzak2.pkg0;

import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setTitle("Restaurante Arzak");
        setLocationRelativeTo(null);
        this.setResizable(false);
        Mostra.setEnabled(false);
    }

    public void eliminar() {
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
        //cargaTicket();
    }

    String matriz[][];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CrearTabla = new javax.swing.JButton();
        Mostra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Guardar = new javax.swing.JButton();
        Calcular = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Mas = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(0, 204, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Numero de Ventas:");

        jTextField1.setBackground(new java.awt.Color(0, 204, 255));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));

        CrearTabla.setBackground(new java.awt.Color(204, 255, 255));
        CrearTabla.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CrearTabla.setText("Crear Tabla");
        CrearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearTablaActionPerformed(evt);
            }
        });

        Mostra.setBackground(new java.awt.Color(204, 255, 255));
        Mostra.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Mostra.setText("Mostrar");
        Mostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Mostra, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(Mostra))
                .addGap(16, 16, 16))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Restaurante Arzak");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Guardar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Save_37110.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/calculator_math_calculate_accounting_finance_icon_192552.png"))); // NOI18N
        Calcular.setText("Total De ventas");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/business_man_user_support_supportfortheuser_aquestion_theclient_2330.png"))); // NOI18N
        Buscar.setText("Buscar Cliente");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/1455739720_Kitchen_Bold_Line_Color_Mix-28_icon-icons.com_53404.png"))); // NOI18N
        Mas.setText("Mas Vendido");
        Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasActionPerformed(evt);
            }
        });

        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_4219.png"))); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Buscar)
                .addGap(18, 18, 18)
                .addComponent(Mas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcular)
                    .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void CrearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearTablaActionPerformed
        int fila, columna;
        columna = 9;
        fila = Integer.parseInt(jTextField1.getText());

        DefaultTableModel Tabla1 = new DefaultTableModel(fila, columna);
        jTable1.setModel(Tabla1);
        String Titulos[] = new String[9];
        Titulos[0] = "Id";
        Titulos[1] = "Nombre";
        Titulos[2] = "Apellido";
        Titulos[3] = "Tipo ID";
        Titulos[4] = "Numero ID";
        Titulos[5] = "Plato";
        Titulos[6] = "Cantidad";
        Titulos[7] = "Valor";
        Titulos[8] = "Total";
        Tabla1.setColumnIdentifiers(Titulos);

        matriz = new String[jTable1.getRowCount()][jTable1.getColumnCount()];

        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < 9; j++) {
                if (j != 5 && j != 6 && j != 7 && j != 8) {
                    matriz[i][j] = JOptionPane.showInputDialog("Digite El " + Titulos[j] + " Del Usuario #" + (i + 1));
                    jTable1.setValueAt(matriz[i][j], i, j);
                } else if (j == 5) {
                    int op = Integer.parseInt(JOptionPane.showInputDialog("Los " + Titulos[j] + "s Disponibles Son \n" + "Seleccione Una Opcion; \n" + "1. Arroz Con Coco y Pescado Frito $15.000 \n" + "2. Vegetariano (Ensalada de frutas, Vegetales) $9.500 \n" + "3. Arroz Con Pollo y Ensalada de Tomate $10.000 \n" + "4. Carne Asada con su arroz $12.000 \n" + "5. Pizza Con Gaseosa Incluida $8.500 \n" + "6. Hamburguesa Con Gaseosa Incluida $5.000 \n"));
                    switch (op) {
                        case 1:
                            matriz[i][j] = "Menu 1";
                            jTable1.setValueAt(matriz[i][j], i, j);
                            break;
                        case 2:
                            matriz[i][j] = "Menu 2";
                            jTable1.setValueAt(matriz[i][j], i, j);

                            break;
                        case 3:
                            matriz[i][j] = "Menu 3";
                            jTable1.setValueAt(matriz[i][j], i, j);

                            break;
                        case 4:
                            matriz[i][j] = "Menu 4";
                            jTable1.setValueAt(matriz[i][j], i, j);

                            break;
                        case 5:
                            matriz[i][j] = "Menu 5";
                            jTable1.setValueAt(matriz[i][j], i, j);

                            break;
                        case 6:
                            matriz[i][j] = "Menu 6";
                            jTable1.setValueAt(matriz[i][j], i, j);
                            break;
                        default:
                            break;
                    }
                } else if (j == 6) {
                    matriz[i][j] = JOptionPane.showInputDialog("Usuario #" + (i + 1) + " Cuanto Platos Decea comprar");
                    jTable1.setValueAt(matriz[i][j], i, j);
                } else if (j == 7) {
                    switch (matriz[i][5]) {
                        case "Menu 1":
                            matriz[i][j] = "15000";
                            jTable1.setValueAt(matriz[i][j], i, j);
                            break;
                        case "Menu 2":
                            matriz[i][j] = "9500";
                            jTable1.setValueAt(matriz[i][j], i, j);
                            break;
                        case "Menu 3":
                            matriz[i][j] = "10000";
                            jTable1.setValueAt(matriz[i][j], i, j);
                            break;
                        case "Menu 4":
                            matriz[i][j] = "12000";
                            jTable1.setValueAt(matriz[i][j], i, j);
                            break;
                        case "Menu 5":
                            matriz[i][j] = "8500";
                            jTable1.setValueAt(matriz[i][j], i, j);
                            break;
                        case "Menu 6":
                            matriz[i][j] = "5000";
                            jTable1.setValueAt(matriz[i][j], i, j);
                            break;
                        default:
                            break;
                    }
                }
            }
        }

    }//GEN-LAST:event_CrearTablaActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        Mostra.setEnabled(true);
        matriz = new String[jTable1.getRowCount()][jTable1.getColumnCount()];

        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < (matriz[0].length - 1); j++) {
                matriz[i][j] = jTable1.getValueAt(i, j).toString();
            }
        }
        JOptionPane.showMessageDialog(null, "Datos Almacenados Correctamente");
    }//GEN-LAST:event_GuardarActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        double total = 0;

        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < (matriz[0].length); j++) {
                total = Integer.parseInt(matriz[i][6]) * Integer.parseInt(matriz[i][7]);
                matriz[i][8] = "" + total;
            }
        }

        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < (matriz[0].length); j++) {
                jTable1.setValueAt(matriz[i][8], i, 8);
            }
        }


    }//GEN-LAST:event_CalcularActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        this.Buscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        int ID = Integer.parseInt(JOptionPane.showInputDialog("Digite El numero de documento del usuario"));
        int num = 0;

        for (int i = 0; i < matriz.length; i++) {
            for (int j = 1; j < (matriz[0].length); j++) {
                num = Integer.parseInt(matriz[i][4]);
                if (num == ID) {
                    JOptionPane.showMessageDialog(null, "El Numero De Documento Corresponde a: \n" + matriz[i][j]);
                }
            }
        }

    }//GEN-LAST:event_BuscarActionPerformed

    private void MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasActionPerformed
        this.Mas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        String Vec_menu[] = new String[6];
        Vec_menu[0] = "Menu 1";
        Vec_menu[1] = "Menu 2";
        Vec_menu[2] = "Menu 3";
        Vec_menu[3] = "Menu 4";
        Vec_menu[4] = "Menu 5";
        Vec_menu[5] = "Menu 6";

        int Vec_Cantidad[] = new int[6];

        for (int i = 0; i < Vec_menu.length; i++) {
            int cont = 0;
            String valor = Vec_menu[i];
            for (int j = 0; j < matriz.length; j++) {
                if (matriz[j][5].equals(valor)) {
                    cont = cont + Integer.parseInt(matriz[j][6]);
                }
            }
            Vec_Cantidad[i] = cont;
        }

        for (int i = 0; i < Vec_Cantidad.length; i++) {
            System.out.println(Vec_Cantidad[i]);
        }

        int mayor = Vec_Cantidad[0];
        int p = 0;
        for (int i = 0; i < Vec_Cantidad.length; i++) {
            if (Vec_Cantidad[i] > mayor) {
                mayor = Vec_Cantidad[i];
                p = i;
            }
        }

        JOptionPane.showMessageDialog(null, "El Mas Vendido Es: El " + Vec_menu[p] + " Con Un total De " + mayor + " Platos Vendidos");

    }//GEN-LAST:event_MasActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        this.Limpiar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        eliminar();


    }//GEN-LAST:event_LimpiarActionPerformed

    private void MostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostraActionPerformed

        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < (matriz[0].length); j++) {
                JOptionPane.showMessageDialog(null, "Fila #" + (i + 1) + " y Columna # " + (j + 1) + ": "+ matriz[i][j]);
            }
        }

    }//GEN-LAST:event_MostraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Calcular;
    private javax.swing.JButton CrearTabla;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Mas;
    private javax.swing.JButton Mostra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
